services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: semantix-chat-backend
    env_file:
      - ./backend/.env
      - .env
    ports:
      - "0.0.0.0:${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:${BACKEND_CONTAINER_PORT}/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: semantix-chat-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_HOST_PORT}
    ports:
      - "0.0.0.0:${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${FRONTEND_CONTAINER_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: semantix-chat-network