services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: semantix-chat-backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=5669
      - LOG_LEVEL=INFO
    ports:
      - "0.0.0.0:5669:5669"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5669/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: semantix-chat-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5669
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: semantix-chat-network